### PR TITLE
Fix sequence generation to be always increasing

### LINKED ISSUE #5: Sequence generation is not correct: it should reset when the timestamp increases
Hi there! First of all, thank you for this great crate! The `Snowflake` trait is a great way to make snowflakes customizable, and it seems like a much better approach than the other crates out there.

However, I think I've found a small bug in the way sequence generation is done.
Or, to be precise, `snowflaked` does it differently from [the way Twitter does it](https://github.com/twitter-archive/snowflake/blob/snowflake-2010/src/main/scala/com/twitter/service/snowflake/IdWorker.scala#L81C1-L88) (which I think is how most other snowflake generation libraries also do it).

Specifically, I believe that the sequence number should be reset whenever `now > components.timestamp()`, rather than only rolling over when `4095` is hit.

Not doing so gives rise to the following race condition (which I experienced in my test suite):

```
CommonSnowflake { timestamp: 1708353054919, instance: 42, sequence: 4093 }
CommonSnowflake { timestamp: 1708353054919, instance: 42, sequence: 4094 }
CommonSnowflake { timestamp: 1708353054920, instance: 42, sequence: 4095 }
CommonSnowflake { timestamp: 1708353054920, instance: 42, sequence: 0 }
CommonSnowflake { timestamp: 1708353054920, instance: 42, sequence: 1 }
```

There are other ways to fix this race condition, but following the original snowflake spec is probably the best way to do so.

### PR DESCRIPTION
**Pull request by Qqwy**
- [x] Fixes generation of the normal generator
- [x] Fixes generation of the sync generator
- [x] Replaces the two incorrect `test_generate` tests with `test_generate_ordered` tests
- [x] Gets rid of `MaybeUninit` inside the sync generation. I've looked at the created assembly (using [cargo asm](https://github.com/gnzlbg/cargo-asm)) and the compiler is more than clever enough to optimize the wrapping and unwrapping into an `Option` away here, so there's no need for unsafe. (Extra fun as it was the only unsafe in this crate, so now it's fully `no-unsafe`!)

Fixes #5

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -410,6 +424,10 @@ impl Components {
         *self = Self(timestamp + instance + seq)
     }
 
+    pub(crate) fn reset_sequence(&mut self) {
+        self.set_sequence(4095)
```
Comment (MrGunflame) [inline src/lib.rs]: I think this should actually reset to 1. If the current timestamp increases and an ID with `sequence=0` is returned we can use entire range `1..4095` for that timestamp before needing to sleep again.

File: src/sync.rs [hunk 2]
```diff
@@ -224,46 +223,60 @@ where
         self.epoch
     }
 
-    fn generate<S, F>(&self, tick_wait: F) -> S
+    fn generate<S, F>(&self, tick_wait: &F) -> S
```
Comment (MrGunflame) [inline src/sync.rs]: IMO the better option here would be to take an owned `F` and borrowing it before moving it into the closure. This also doesn't break the loom tests.

**Review by MrGunflame — CHANGES_REQUESTED** [review]
Thanks for the PR, please run `cargo fmt` on the thing once. Looks almost fine besides that.

File: src/lib.rs (hunk 1 above)
Comment (Qqwy) [reply src/lib.rs]: You are absolutely correct! A typical example of an off-by-one error where I thought you'd need to store a value one _lower_ than the next value but rather we need to store one _higher_ 🙈

**Comment by Qqwy** [comment]
Thanks for reviewing 😊 ! Your feedback has been applied.

I'm running the loom tests locally now (I did not realize that they didn't run as part of the normal test suite before), using `RUSTFLAGS="--cfg loom" cargo test --lib --all-features --release`, and see that the `no_duplicates_no_wrap` test is failing. 
I'll investigate what is going on there.

**Comment by Qqwy** [comment]
The trick was that since the sequence stores the 'next' value, at the very start we have to initialize it at `1`. Otherwise, in the edge case where someone tries to generate a snowflake in the very same millisecond as the epoch, it would immediately trigger the `wait` condition.

In real programs this won't ever come up of course, since time will always have passed since the epoch.

**Comment by MrGunflame** [comment]
This is very strange, I have no idea why `cargo fmt` would break formatting and then not fix it.

**Comment by Qqwy** [comment]
Hang on; I think I might be running a slightly older version of `cargo fmt` locally (from 2023-11) (My _nightly_ version was up-to-date but my _stable_ version wasn't). Let me see whether updating to the latest version fixes it.

File: src/sync.rs [hunk 3]
```diff
@@ -229,41 +228,60 @@ where
...
+                        components.reset_sequence();
                         components.set_timestamp(now);
-                        timestamp = now;
-                        break;
+                        id = Some(S::from_parts(now, instance, 0));
+                        Some(components.to_bits())
+                    }
+                    cmp::Ordering::Equal => {
+                        let sequence = components.take_sequence();
+                        dbg!((now, instance, sequence));
```
Comment (MrGunflame) [inline src/sync.rs]:
```suggestion
```

**Comment by Qqwy** [comment]
That should've done it 👍

File: src/sync.rs [hunk 4]
```diff
@@ -229,41 +228,60 @@ where
...
-        unsafe { id.assume_init() }
+    fn wait_until_next_millisecond<F>(epoch: &T, last_millisecond: u64, tick_wait: F) -> u64
+    where
+        F: Fn(),
+    {
+        loop {
+            println!(
+                "Waiting until the next millisecond from {}",
+                last_millisecond
+            );
```
Comment (MrGunflame) [inline src/sync.rs]:
```suggestion
```

**Review by MrGunflame — CHANGES_REQUESTED** [review]
Just a few leftovers from debugging it seems.

**Comment by Qqwy** [comment]
> Just a few leftovers from debugging it seems.

Apologies, that was sloppy. I should stop trying to make these kinds of PRs late at night. Thanks for your keen eye!

**Review by MrGunflame — APPROVED** [review]
No need to apologize, thanks.

**Comment by MrGunflame** [comment]
Released in version `1.0.3`.
